config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
  root 'users#index'
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[create destroy]
      resources :likes, only: %i[create]
    end
  end

  namespace :api, defaults: {format: 'json'} do
    post 'login', to: 'authentication#authenticate'
    resources :users, only: %i[index show] do
      resources :posts, only: %i[index show ] do
        resources :comments, only: %i[index create]
      end
  end
end
end

app/views/renders/_comment.html.erb
<div>
  <p>
    <%= comment.author.name %>:
    <%= comment.text %></p>
          <% if can? :destroy, comment %>
  <%= button_to user_post_comment_path(user_id: comment.post.author_id, post_id: comment.post_id, id: comment.id), class:"delete", method: :delete do %>
    delete
  <% end %>
  <% end %>
</div>

app/views/renders/_flash.html.erb
<div>
  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id =>  "flash_#{name}" if msg.is_a?(String) %>
    </div>
  <% end %>
</div>

app/views/renders/_home.html.erb
<%= link_to 'Home page', root_path%>

app/views/renders/_new_comment.html.erb
<%= form_with url: user_post_comments_path(post_id:params[:id]), scope: :comment do |f|%>
<%= f.text_area :text, placeholder: 'Comment...', required:true %>
<%= f.submit 'Add comment'%>
<% end %>

app/views/renders/_new_like.html.erb
<%= form_with url: user_post_likes_path(post_id:params[:id]), class: "like-form", scope: :like do |form| %>
  <%= form.submit "like", class: "like" %>
<% end %>

app/views/renders/_new_post.html.erb
<%= form_with model:post, url: user_posts_url do |f| %>
  <div>
    <%= f.label :title%>
    <%= f.text_field :title, required:true %>
  </div>

  <div>
    <%= f.label :text%>
    <%= f.text_field :text, required:true %>
  </div>

  <%= f.submit 'Create' %>
<%end%>

app/views/renders/_post.html.erb
<li class="post-data">
<h2>
<li><%= link_to post.title, "/users/#{post.author.id}/posts/#{post.id}" %></li>
</h2>
<p><%= post.text%> </p>
<p>Comments: <%= post.comments_counter || 0%> likes: <%= post.likes_counter || 0%></p>
      <%= link_to "See Post", user_post_path(user_id: post.author_id, id: post.id), class:"link" %>
      <% if can? :destroy, post %>
        <%= button_to "Delete Post", user_post_path(user_id: post.author_id, id: post.id), class:"link", method: :delete %>
      <% end %>
</li>

app/views/renders/_user.html.erb
<%= link_to user do %>
  <li class="card-wrap">
 <% if user.photo %>
    <%= image_tag user.photo, class:'card-image', alt: 'photo' %>
 <% end %>
  
    <div class="card">
      <h2 class="card-title">
        <%= user.name %>
      </h2>
      <p class="card-para">number of posts:
        <%= user.posts_counter || 0 %>
      </p>
    </div>
  </li>
<% end %>