config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
  root 'users#index'
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[create destroy]
      resources :likes, only: %i[create]
    end
  end

  namespace :api, defaults: {format: 'json'} do
    post 'login', to: 'authentication#authenticate'
    resources :users, only: %i[index show] do
      resources :posts, only: %i[index show ] do
        resources :comments, only: %i[index create]
      end
  end
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :comments, foreign_key: 'author_id', dependent: :delete_all
  has_many :posts, foreign_key: 'author_id', dependent: :delete_all
  has_many :likes, foreign_key: 'author_id', dependent: :delete_all
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def last_posts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :authorize_request, except: :create

  def index
    @users = User.all.order(created_at: :asc)
    render json: @users
  end

  def show
    @user = User.find(params[:id])
    render json: @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user_current = current_user
  end

  def show
    @user_current = User.find(params[:id])
  end
end

app/views/users/index.html.erb
<%= link_to 'New post', new_user_post_path(user_id: current_user.id) %>
<ul>
  <%= render partial: "renders/user", collection: @users %>
</ul>

app/views/users/show.html.erb
<% user = @user_current %>
<% posts = user.last_posts %>

<%= render partial: "renders/user", object: user %>

<div class="bio">
  <h2>bio</h2>
  <p class="bio-text">
    <%= user.bio %>
  </p>
</div>

<div class="post-father">
  <ul class="post-wrap">
    <%= render partial: "renders/post", collection: posts %>
  </ul>

  <%= link_to "See all posts", "/users/#{user.id}/posts" %></div>